# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_o1SR_y_GpqlzLW2cLrbOAcMEZANpYlU
"""
#no.1
nilai = int(input('masukan nilai dalam angka 1-100: '))
 
hasil = None
if nilai >= 90:
    hasil = 'A'
elif nilai >= 80:
    hasil = 'B'
elif nilai >= 70:
    hasil = 'C'
elif nilai >= 60:
    hasil = 'D'
elif nilai >= 40:
    hasil = 'E'
elif nilai >= 10:
    hasil = 'F'
else:
    print('inputan salah')
 
print('Nilai {} =  {}'.format(nilai, hasil))

#nomor 2

gol= (input('Golongan Dari : '))
daya = int(input('Daya : '))
pemakaian = int(input('Pemakaian : '))

if gol == 'R1' and daya <= 900 :
    tarif = 1352
elif gol == 'R1' and daya <= 1300 :
    tarif = 1444.70
elif gol == 'R1' and daya <= 2200 :
    tarif = 1444.70
elif gol == 'R2' and daya >= 3500 and daya <= 5500 :
    tarif = 1699.53
elif gol == 'R3' and daya >= 6600 :
    tarif = 1699.53
elif gol == 'B2' and daya >= 6600 and daya <= 200000 :
    tarif = 1444.70
elif gol == 'B3' and daya >= 200000 :
    tarif = 1114.74
elif gol == 'I3' and daya >= 200000 :
    tarif = 1314.12
elif gol == 'P1' and daya >= 6600 and daya <= 200000 :
    tarif = 1523.28
else:
    pesan= 'Data Anda Tidak Ada'

tagihan = tarif * pemakaian
print('Jumlah Tagihan Yang Harus Anda Bayar Adalah : Rp.', tagihan)

#no.3#
a = int(input('Masukkan Nilai A :'))
b = int(input('Masukkan Nilai B :'))
c = int(input('Masukkan Nilai C :'))

if a > b > c :
  print('Nilai Bilangan Terbesar Adalah :', a)
elif b > a > c :
  print('Nilai Bilangan Terbesar Adalah :', b)
else :
  print('Nilai Bilangan Terbesar Adalah :', c)