personal_data = []

print('=========================================')
print('            Isi data diri anda           ')
print('=========================================')
nama = personal_data.append(input('Masukkan nama : '))
umur = personal_data.append(input('Masukkan umur : '))
alamat = personal_data.append(input('Masukkan alamat : '))
print('=========================================')
print(personal_data)
def menu() :
    print('=========================================')
    print('            Silahkan pilih opsi         ')
    print('=========================================')
    print('\n 1. Data diri anda\n 2. Ubah nama\n 3. Ubah umur\n 4. Ubah alamat\n 5. Keluar')
    print('=========================================')
    
menu()
choosedoption = int(input('Pilih opsi '))
print('=========================================')

while True :
    if choosedoption == 1 :
        print('=========================================')
        print('             Data diri anda            ')
        print('-----------------------------------------')
        print('Nama :', personal_data[0])
        print('Umur :', personal_data[1])
        print('Alamat :', personal_data[2])
        print('=========================================')
        menu()
        choosedoption = int(input('Pilih opsi :'))
        print('=========================================')
    if choosedoption == 2 :
        print('=========================================')
        print('           Ubah nama             ')
        print('-----------------------------------------')
        personal_data[0] = input('Masukkan nama :')
        print('-----------------------------------------')
        print('    Berhasil mengubah nama anda  ') 
        print('=========================================')
        menu()
        choosedoption = int(input('Pilih opsi :'))
        print('=========================================')
    if choosedoption == 3 :
        print('=========================================')
        print('           Ubah umur             ')
        print('-----------------------------------------')
        personal_data[1] = input('Masukkan umur :')
        print('-----------------------------------------')
        print('  Berhasil mengubah umur anda') 
        print('=========================================')
        menu()
        choosedoption = int(input('Pilih opsi :'))
        print('=========================================')
    if choosedoption == 4 :
        print('=========================================')
        print('          Ubah alamat            ')
        print('-----------------------------------------')
        personal_data[2] = input('Masukkan alamat :')
        print('-----------------------------------------')
        print('  Berhasil mengubah alamat anda  ') 
        print('=========================================')
        menu()
        choosedoption = int(input('Pilih opsi :'))
        print('=========================================')
    if choosedoption == 5 :
        print('=========================================')
        print('  terimakasih telah menggunkan program ini   ')
        print('=========================================')
        break
    if choosedoption > 5 or choosedoption <=0 :
        print('=========================================')
        print('      opsi tidak tersedia        ')
        print('=========================================')
        menu()
        choosedoption = int(input('Pilih opsi :'))
        print('=========================================')