# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OH3tmkZfOZZoeZD1Hf0JInNNPjtBEcF9
"""

# Nomor 1

import math
from re import A

# Menginput Panjang, lebar dan Tinggi Balok

p = int(input('masukan panjang kapal: '))

l = int(input('masukan lebar kapal: '))

t = int(input('masukan tinggi kapal: '))

 

# Hitung Luas Permukaan    

def luas_permukaan(p,l,t):

    L = 2 * ( (p*l) + (p*t) + (l*t) )

    return L

 

# Hitung Volume Balok

def volume(p,l,t):

    V = p * l * t

    return V

print('Jadi kapal dengan ukuran panjang:{}, lebar:{}, tinggi:{} dan Mempunyai luas:{}'.format(p,l,t, luas_permukaan(p,l,t)))

##No.2##
def main():
    # menampilkan informasi program
    print("Konversi Detik ke Jam\n")
 
    # input total detik
    totaldetik = int(input("Masukkan detik \t: "))
 
    # melakukan konversi hh:mm:ss ke detik
    hh = totaldetik // 3600
    sisadetik = totaldetik % 3600
    mm = sisadetik // 60
    ss = sisadetik % 60
 
    # menampilkan hasil konversi
    print("%d detik sama dengan %d:%d:%d" %(totaldetik,hh,mm,ss))
 
if __name__ == "__main__":
    main()

#no.3#
import math

print ("--- Program Menghitung Volume dan Luas Kerucut motubablog ---\n")

tinggi=int(input("Masukan Tinggi : "))
jari=int(input("Masukan Jari-jari Lingkarang : "))

phi=22/7

pelukis=math.sqrt((jari*jari)+(tinggi*tinggi))

luas=int(phi*jari*(jari+pelukis))
volume=int((1/3)*phi*(jari*jari)*tinggi)

print ("Luas Kerucut = ", luas)
print ("Volume Kerucut = ", volume)1