# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_o1SR_y_GpqlzLW2cLrbOAcMEZANpYlU
"""

#no.1
import math

#masukkan nilai h, a, and b
h = int(input('Input ketinggian menara (h): '))
a = int(input('Input sudut elevasi ujung belakang kapal (a): '))
b = int(input('Input sudut elevasi ujung depan kapal (b): '))

#konversi a dan b ke radian
menara_ujung_belakang_kapal = math.tan(math.radians(a))*h
menara_ujung_depan_kapal = math.tan(math.radians(b))*h

#menghitung panjang kapal
panjang_kapal = math.sqrt((menara_ujung_belakang_kapal - menara_ujung_depan_kapal)**2)
print("Panjang kapal =%5.1f m" % panjang_kapal)

#No.2
def main():
    # menampilkan informasi program
    print("Konversi Detik ke Jam\n")
 
    # input total detik
    totaldetik = int(input("Masukkan detik \t: "))
 
    # melakukan konversi hh:mm:ss ke detik
    hh = totaldetik // 3600
    sisadetik = totaldetik % 3600
    mm = sisadetik // 60
    ss = sisadetik % 60
 
    # menampilkan hasil konversi
    print("%d detik sama dengan %d:%d:%d" %(totaldetik,hh,mm,ss))
 
if __name__ == "__main__":
    main()

#no.3#
import math

print ("--- Program Menghitung Volume dan Luas Kerucut motubablog ---\n")

tinggi=int(input("Masukan Tinggi : "))
jari=int(input("Masukan Jari-jari Lingkarang : "))

phi=22/7

pelukis=math.sqrt((jari*jari)+(tinggi*tinggi))

luas=int(phi*jari*(jari+pelukis))
volume=int((1/3)*phi*(jari*jari)*tinggi)

print ("Luas Kerucut = ", luas)
print ("Volume Kerucut = ", volume)